#!/usr/bin/env python3
"""Write domain scorecard markdown from AUDIT_REPORT_latest.json."""
from __future__ import annotations

import json
import subprocess
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/audit/reports/AUDIT_REPORT_latest.json"
OUT = ROOT / "docs/audit/reports/DOMAIN_SCORECARD_latest.md"

EMOJI = {"GREEN": "🟢", "YELLOW": "🟡", "ORANGE": "🟠", "RED": "🔴", "BLOCKED": "⚫"}


def main() -> int:
    if not REPORT.exists():
        print("FAIL: run make final-audit first")
        return 2
    r = json.loads(REPORT.read_text(encoding="utf-8"))
    try:
        head = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        print("FAIL: cannot resolve current Git HEAD")
        return 2
    report_sha = str(r.get("git_sha") or "").strip()
    if report_sha != head:
        print(f"FAIL: stale audit report SHA={report_sha or 'missing'} HEAD={head}")
        print("Run make final-audit on this exact SHA before generating a domain scorecard.")
        return 2
    by = defaultdict(list)
    for it in r.get("items") or []:
        by[it.get("domain") or "?"].append(it)

    lines = [
        f"# Domain scorecard — {(r.get('git_sha') or '')[:12]}",
        "",
        f"**Score:** {r.get('final_audit_score')} / 100  ",
        f"**Verdict:** `{r.get('final_verdict')}`  ",
        f"**VERSION:** `{r.get('version')}`",
        "",
        "| Domain | n | avg | G | Y | O | R | B |",
        "|--------|--:|----:|--:|--:|--:|--:|--:|",
    ]
    for dom in sorted(by.keys()):
        items = by[dom]
        scored = [i for i in items if i.get("score") is not None]
        avg = round(sum(float(i["score"]) for i in scored) / len(scored), 1) if scored else "—"
        c = {k: 0 for k in EMOJI}
        for i in items:
            c[i.get("color") or "BLOCKED"] = c.get(i.get("color") or "BLOCKED", 0) + 1
        lines.append(
            f"| {dom} | {len(items)} | {avg} | {c['GREEN']} | {c['YELLOW']} | {c['ORANGE']} | {c['RED']} | {c['BLOCKED']} |"
        )
    lines += ["", "_Generated by scripts/audit_domain_scorecard.py — not a human green declaration._", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
