#!/usr/bin/env bash
# Generate a filled pilot SHA record (no secrets) from local git + VERSION.
# Writes docs/00-master/PILOT_SHA_RECORD.last.md (gitignored optional) or stdout.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VER="$(tr -d '[:space:]' < VERSION 2>/dev/null || echo unknown)"
SHA="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
SHORT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
HOST_URL="${TALAMALA_BASE_URL:-}"

OUT="${1:-docs/00-master/PILOT_SHA_RECORD.last.md}"

{
  echo "# Pilot SHA record (auto)"
  echo ""
  echo "| Field | Value |"
  echo "|-------|--------|"
  echo "| VERSION | $VER |"
  echo "| Git SHA | \`$SHA\` |"
  echo "| Short | \`$SHORT\` |"
  echo "| Branch | $BRANCH |"
  echo "| Date (UTC) | $DATE |"
  echo "| Host / URL | ${HOST_URL:-_(set TALAMALA_BASE_URL)_} |"
  echo "| Operator | |"
  echo "| \`make pilot-env-check\` | |"
  echo "| \`make pilot-preflight\` | |"
  echo "| \`make release-build\` | |"
  echo "| \`make pilot-host-smoke\` | |"
  echo "| \`KIMIA_WRITE_VERIFY_ENABLE\` | 0 |"
  echo "| Owner signed RELEASE_SCOPE | |"
  echo "| Notes | auto-generated by scripts/pilot_record.sh — fill results manually |"
  echo ""
  echo "Do not record secrets. Do not enable Write on this form."
} > "$OUT"

echo "Wrote $OUT"
echo "SHA=$SHA VERSION=$VER"
